### PR TITLE
#30 Adding App Terraform Deployment

### PR DESCRIPTION
**Pull request by code4clouds**
Acceptance Criteria

    Development Engineers can define terraform inputs so that they do not have to be provided each time they run terraform validate, plan, or apply
    Development Engineers can define terraform inputs in isolation and those inputs are not checked into source control
    Release Engineers can deploy the terraform templates using only terraform and command line. Variables/inputs needed for this case should be documented within the readme.
    Resource group is deployed to demonstrate template does create resources in azure (see given/when/then scenario below)

given input app name 'cblt'
and input env 'dev'
and input location 'eastus'
and input org 'cse'
when terraform apply is run
then a resource group 'rg-cblt-dev-eus-cse' exists

### CODE REVIEW

**Comment by code4clouds** [comment]
You need to use "sh deploy.sh"  deploy.sh by itself doesn't work without the +x   I didn't want the user to change permissions, but I found a way to commit my .sh with the +x so it should work on the next clone.  What was the error you got?

**Comment by code4clouds** [comment]
The *.tfstate* may be only on your environment after you ran Terraform.  I haven't none checked in with this commit.

**Comment by code4clouds** [comment]
@rickrain   "The intent of the user story is for this resource group to be used to define the core/shared resource (ie: Key Vault and Virtual Network) in later user stories."  There has to be some documentation for this code, right?

**Comment by rickrain** [comment]
@code4clouds Yes, there will be documentation for this.  We will address this in an upcoming sprint.

**Comment by code4clouds** [comment]
@rickrain Removed the ./README.md

We need to talk about the ./shared/README and discuss it further.

**Pull request merged**
