### PR TITLE
Added script to initialize ACR and related service principals

### PR DESCRIPTION
**Pull request by rickrain**
## Steps to test

Change into the `./setup` folder.

Run the script `./acr-sp-init.sh` with necessary parameter values.  For example:

`./acr-sp-init.sh -c contoso -l eastus`

After the script completes successfully, test the results using the following commands:

```
// Test the resource group 
az group show --name acr-usea-contoso --query '[name,location]'

// Test the ACR resource
az acr show --name acruseacontoso --query '[name,location]'

// Test the service principals
az ad sp show --id http://acr-contoso-pull --query '[objectType,displayName]'
az ad sp show --id http://acr-contoso-push --query '[objectType,displayName]'

// Test the service principal role assignments
az role assignment list --assignee http://acr-contoso-pull --all --query '[].[principalName,roleDefinitionName]'
az role assignment list --assignee http://acr-contoso-push --all --query '[].[principalName,roleDefinitionName]'

```
#31

### CODE REVIEW

**Comment by charleszipp** [comment]
@rickrain I did encounter one issue when running this from cloud shell. The script seems to hang on line 96 when running `az login`. The cloud shell reported this warning and blocked further execution of the script

```
charles@Azure:~$ ./acr-sp-init.sh -c czp -l eastus
Cloud Shell is automatically authenticated under the initial account signed-in with. Run 'az login' only if you need to use a different account
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code F7Y7EXNA5 to authenticate.
```
If I comment out that line, the script did execute. Once it executed, I was able to verify it creates ACR instance along with SPN's in intended roles & scopes
image
image

Should we exclude az login from the script? What if someone wants to run it as a SPN, MSI, or from cloud shell as I did? cc @xtophs

**Comment by rickrain** [comment]
@charleszipp We can certainly remove `az login` from the script and just provide guidance that the user/agent should be authenticated prior to executing the script.  I did it both ways during development.  The script, as written, was intended to be run interactively.  Hence the reason for interactively requiring the user to authenticate to Azure.

**Comment by charleszipp** [comment]
@rickrain this may provide a third option, check if they are already logged in and then run az login if they are not logged in already
image

**Comment by xtophs** [comment]
location doesn't work with locations in the list:

```
$ az account list-locations --query '[].name'
[
  "eastasia",
  "southeastasia",
  "centralus",
  "eastus",
  "eastus2",
  "westus",
  "northcentralus",
  "southcentralus",
  "northeurope",
  "westeurope",
  "japanwest",
  "japaneast",
  "brazilsouth",
  "australiaeast",
  "australiasoutheast",
  "southindia",
  "centralindia",
  "westindia",
  "canadacentral",
  "canadaeast",
  "uksouth",
  "ukwest",
  "westcentralus",
  "westus2",
  "koreacentral",
  "koreasouth",
  "francecentral",
  "francesouth",
  "australiacentral",
  "australiacentral2",
  "southafricanorth",
  "southafricawest"
]

$ ./acr-sp-init.sh -c xtoph -l eastus
./acr-sp-init.sh: line 30: ${location,,}: bad substitution
$ ./acr-sp-init.sh -c xtoph -l eastus2
./acr-sp-init.sh: line 30: ${location,,}: bad substitution
$ ./acr-sp-init.sh -c xtoph -l westus
./acr-sp-init.sh: line 30: ${location,,}: bad substitution
```


Reordering script commands for the array declaration before the location substitution surfaces this error:
```
$ ./acr-sp-init.sh -c xtoph -l westus
./acr-sp-init.sh: line 30: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
```

Which yields that error is likely related to the [default bash on MacOS being 3.2.57, which doesn't have associative arrays](https://stackoverflow.com/questions/27002192/bash-declare-a-does-not-work-on-macos). 

[Doesn't look like Apple is going to update to bash 4](https://apple.stackexchange.com/questions/193411/update-bash-to-version-4-0-on-osx)

**Comment by xtophs** [comment]
Could you clarify that bash4 affects all Mac users running the default bash setup and document how to remedy? we want to make it easy for people that use this.

**Comment by charleszipp** [comment]
> Could you clarify that bash4 affects all Mac users running the default bash setup and document how to remedy? we want to make it easy for people that use this.

@xtophs I added a note in the setup that points to instructions for updating bash. @rickrain is working on reviewing the other two PR's from last sprint so Im trying to help out with docs on this. Let me know if this is sufficient.

**Comment by rickrain** [comment]
> I thought we needed a loop here, as the propagation of the newly created SP may not be complete

@xtophs this was from sprint 1 - last week and was closed already.  The change you're looking for is included in the PR for this week #47.

**Pull request merged**
